name: yoga
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^1.5.3
  
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  internet_connection_checker_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: 2.0.3+1
  build_runner: ^2.3.2
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - asset/

  #
