name: yoga
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  get_it: ^7.6.0
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  
  flutter_bloc: ^8.1.3

  
  
  
 
  freezed_annotation: ^2.0.3

  flutter_secure_storage: ^8.0.0
  internet_connection_checker_plus: ^1.0.1
  cached_network_image: ^3.2.3
  audioplayers: ^4.0.1
  flutter_svg: ^2.0.6
  dropdown_button2: ^2.1.3
  flutter_stripe: ^9.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.5
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo.png"

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/image/
    - asset/fonts/
    - asset/icon/
  
  fonts:
    - family: Nexa
      fonts:
        - asset: asset/fonts/Nexa Light.otf
          weight: 400
        - asset: asset/fonts/Nexa Bold.otf
          weight: 800

  #
